### ISSUE TITLE
Report layout & formatting

### ISSUE THREAD

**Issue by carlos-JRCFC** [younesDev00/InformationSystems#3]

**Comment by Campbell-Uni** [comment]
6ff13327eeb327ccb3f22e04e4b854aeec30abcb

**Comment by Campbell-Uni** [comment]
cf8a981a69dc54383f9f248e8a73b0b7258e1411

**Comment by Campbell-Uni** [comment]
526c28f77cb136b11cd091c4a3ae05394ea637c1

**Comment by Campbell-Uni** [comment]
acbd94eb150462b351a5baaec08436802b13906a

**Comment by Campbell-Uni** [comment]
88ea1be71e517b0cb1102c20d86b9c500488c95d

**Comment by Campbell-Uni** [comment]
d2841cd9aae5354e71261c4c04e5539395e30330
